services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      container_name: scheduling-care-aws
      MONGO_INITDB_DATABASE: scheduling-care-aws
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

  backend:
    build: ./backend
    environment:
      MONGO_URI: ${MONGO_URI}
    ports:
      - ${PORT}:${PORT}
